language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '9'
  - '10'
before_script:
  - npm prune
script:
  - npm test
after_success:
  - npm run coverage
  - npm run release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
